### ISSUE TITLE
Latest master build crashes on Vita.

### ISSUE THREAD

**Issue by rsn8887** [Cpasjuste/pfba#16]
The latest master [here](https://github.com/Cpasjuste/pfba/commit/e1fae4185128fcbf2e489c03e179ac80ebca7f2e) is crashing on startup on Vita.

The version a few commits earlier [here](https://github.com/Cpasjuste/pfba/commit/7d646b24b26c3dcd086504990ae5771c15f12fa0) works just great.

Maybe I am using the wrong build commands? I am using the ones from Readme.md.

**Comment by Cpasjuste** [comment]
Thanks @rsn8887 , i guess i did enable SDL2 build for testing in libcross2d, which should not be set. I'll try to fix that very soon.

**Comment by Cpasjuste** [comment]
@rsn8887, i guess/hope it's fixed in 39c9278aa5412f80850ee9a352e9634f3d500a42

**Comment by rsn8887** [comment]
It is still crashing, I think it is something else after all. Maybe you can test it yourself, sometime if you have time. That way I can know if it is my VitaSDK, or my SDL or something else.

**Comment by Cpasjuste** [comment]
Fixed in 49b1447dfdd2896762300d7f7b056b37679a7214, sorry for the crap :)
